<!DOCTYPE html>
<html lang="en">

<head>
  <title>
  C&#43;&#43; - noexpect · Techiedeepdive
</title>
  <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light dark">




<meta name="description" content="noexept is c&#43;&#43;11 specifier to mark method as exception non-throwing. the best explanation i found is on MSF.
 Unary conditional operator noexcept(constant_expression) where constant_expression yields true, and its unconditional synonym noexcept, specify that the set of potential exception types that can exit a function is empty. That is, the function never throws an exception and never allows an exception to be propagated outside its scope.
 and after i tried it out, g&#43;&#43; doesn&rsquo;t error out when that happen.">
<meta name="keywords" content="">

<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content=""/>

<meta name="twitter:title" content="C&#43;&#43; - noexpect"/>
<meta name="twitter:description" content="noexept is c&#43;&#43;11 specifier to mark method as exception non-throwing. the best explanation i found is on MSF.
 Unary conditional operator noexcept(constant_expression) where constant_expression yields true, and its unconditional synonym noexcept, specify that the set of potential exception types that can exit a function is empty. That is, the function never throws an exception and never allows an exception to be propagated outside its scope.
 and after i tried it out, g&#43;&#43; doesn&rsquo;t error out when that happen."/>

<meta property="og:title" content="C&#43;&#43; - noexpect" />
<meta property="og:description" content="noexept is c&#43;&#43;11 specifier to mark method as exception non-throwing. the best explanation i found is on MSF.
 Unary conditional operator noexcept(constant_expression) where constant_expression yields true, and its unconditional synonym noexcept, specify that the set of potential exception types that can exit a function is empty. That is, the function never throws an exception and never allows an exception to be propagated outside its scope.
 and after i tried it out, g&#43;&#43; doesn&rsquo;t error out when that happen." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/posts/2020/11/c-noexpect/" /><meta property="og:image" content=""/><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2020-11-20T00:00:00+00:00" />
<meta property="article:modified_time" content="2020-11-20T00:00:00+00:00" /><meta property="og:site_name" content="Techiedeepdive" />





<link rel="canonical" href="/posts/2020/11/c-noexpect/">


<link rel="preload" href="/fonts/forkawesome-webfont.woff2?v=1.2.0" as="font" type="font/woff2" crossorigin>


  
  
  <link rel="stylesheet" href="/css/coder.min.0669b62fc2c181a12a4ba10be9984e385c9a5e83dc7cb7ae3759ad0b98d7e8b2.css" integrity="sha256-Bmm2L8LBgaEqS6EL6ZhOOFyaXoPcfLeuN1mtC5jX6LI=" crossorigin="anonymous" media="screen" />






  
    
    
    <link rel="stylesheet" href="/css/coder-dark.min.f6534b0b446b75d9b6ad77a97d43ede2ddaeff1b6e2361fb7198d6f8fcb7f83f.css" integrity="sha256-9lNLC0Rrddm2rXepfUPt4t2u/xtuI2H7cZjW&#43;Py3&#43;D8=" crossorigin="anonymous" media="screen" />
  



 




<link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16">

<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">

<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/images/safari-pinned-tab.svg" color="#5bbad5">




<meta name="generator" content="Hugo 0.92.2" />





</head>






<body class="preload-transitions colorscheme-auto">
  
<div class="float-container">
    <a id="dark-mode-toggle" class="colorscheme-toggle">
        <i class="fa fa-adjust fa-fw" aria-hidden="true"></i>
    </a>
</div>


  <main class="wrapper">
    <nav class="navigation">
  <section class="container">
    <a class="navigation-title" href="/">
      Techiedeepdive
    </a>
    
      <input type="checkbox" id="menu-toggle" />
      <label class="menu-button float-right" for="menu-toggle">
        <i class="fa fa-bars fa-fw" aria-hidden="true"></i>
      </label>
      <ul class="navigation-list">
        
          
            <li class="navigation-item">
              <a class="navigation-link" href="/posts">Blog</a>
            </li>
          
            <li class="navigation-item">
              <a class="navigation-link" href="/reading-list/">Reading list</a>
            </li>
          
            <li class="navigation-item">
              <a class="navigation-link" href="/tags/">Tags</a>
            </li>
          
        
        
      </ul>
    
  </section>
</nav>


    <div class="content">
      
  <section class="container post">
    <article>
      <header>
        <div class="post-title">
          <h1 class="title">
            <a class="title-link" href="/posts/2020/11/c-noexpect/">
              C&#43;&#43; - noexpect
            </a>
          </h1>
        </div>
        <div class="post-meta">
          <div class="date">
            <span class="posted-on">
              <i class="fa fa-calendar" aria-hidden="true"></i>
              <time datetime="2020-11-20T00:00:00Z">
                November 20, 2020
              </time>
            </span>
            <span class="reading-time">
              <i class="fa fa-clock-o" aria-hidden="true"></i>
              One-minute read
            </span>
          </div>
          
          
          <div class="tags">
  <i class="fa fa-tag" aria-hidden="true"></i>
    <span class="tag">
      <a href="/tags/c&#43;&#43;/">c&#43;&#43;</a>
    </span></div>

        </div>
      </header>

      <div class="post-content">
        
        <p><code>noexept</code> is c++11 specifier to mark method as exception non-throwing. the best explanation i found is on <a href="https://docs.microsoft.com/en-us/cpp/cpp/noexcept-cpp?view=msvc-160"  class="external-link" target="_blank" rel="noopener">MSF</a>.</p>
<blockquote>
<p>Unary conditional operator noexcept(constant_expression) where constant_expression yields true, and its unconditional synonym noexcept, specify that the set of potential exception types that can exit a function is empty. That is, the function never throws an exception and never allows an exception to be propagated outside its scope.</p>
</blockquote>
<p>and after i tried it out, g++ doesn&rsquo;t error out when that happen. It does issue a warning about <code>throw</code> calling terminate.</p>
<h1 id="example">
  Example
  <a class="heading-link" href="#example">
    <i class="fa fa-link" aria-hidden="true" title="Link to heading"></i>
    <span class="sr-only">Link to heading</span>
  </a>
</h1>
<div class="highlight"><pre tabindex="0" style="color:#e5e5e5;background-color:#000;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#0f0;font-weight:bold">#include</span> <span style="color:#0f0;font-weight:bold">&lt;iostream&gt;</span><span style="color:#0f0;font-weight:bold">
</span><span style="color:#0f0;font-weight:bold"></span><span style="color:#fff;font-weight:bold">using</span> <span style="color:#fff;font-weight:bold">namespace</span> std;
<span style="color:#fff;font-weight:bold">class</span> cls
{

<span style="color:#fff;font-weight:bold">public</span>:
    <span style="color:#fff;font-weight:bold">int</span> x;
    <span style="color:#fff;font-weight:bold">void</span> func()
    {
        <span style="color:#fff;font-weight:bold">throw</span> <span style="color:#ff0;font-weight:bold">3</span>;
    }
    <span style="color:#fff;font-weight:bold">void</span> func2() <span style="color:#fff;font-weight:bold">noexcept</span>
    {
        <span style="color:#fff;font-weight:bold">throw</span> <span style="color:#ff0;font-weight:bold">3</span>;
    }
};
<span style="color:#fff;font-weight:bold">int</span> main()
{
    cls c;
    <span style="color:#fff;font-weight:bold">try</span>
    {

        <span style="color:#007f7f">// c.func();  // print 3
</span><span style="color:#007f7f"></span>        c.func2(); <span style="color:#007f7f">// crashes as function
</span><span style="color:#007f7f"></span>    }
    <span style="color:#fff;font-weight:bold">catch</span> (<span style="color:#fff;font-weight:bold">int</span> e)
    {
        cout &lt;&lt; e &lt;&lt; endl;
    }
}
</code></pre></div><p>for func, the exception catcher worked as expected</p>
<pre tabindex="0"><code>$ ./a.out 
3
</code></pre><p>for func2(marked with noexcept), it terminates with stacktrace as if there is no <code>try-catch</code></p>
<pre tabindex="0"><code>noexcept.cc: In member function ‘void cls::func2()’:
noexcept.cc:14:15: warning: throw will always call terminate() [-Wterminate]
   14 |         throw 3;
      |               ^
</code></pre><pre tabindex="0"><code>$ ./a.out 
terminate called after throwing an instance of 'int'
Aborted (core dumped)
</code></pre>
      </div>


      <footer>
        


        
        
        
        
      </footer>
    </article>

    
  </section>

    </div>

    <footer class="footer">
  <section class="container">
    ©
    
    2023
    
    ·
    
    Powered by <a href="https://gohugo.io/">Hugo</a> & <a href="https://github.com/luizdepra/hugo-coder/">Coder</a>.
    
  </section>
</footer>

  </main>

  

  
  
  <script src="/js/coder.min.369d90111ae4409b4e51de5efd23a46b92663fcc82dc9a0efde7f70bffc3f949.js" integrity="sha256-Np2QERrkQJtOUd5e/SOka5JmP8yC3JoO/ef3C//D&#43;Uk="></script>
  

  

  


  

  

  

  

  

  

  

  

  

  

  

  
</body>

</html>